"""
LLM Routes for Agent Builder
🦊 Created by Shiro
"""
import logging
from fastapi import APIRouter, HTTPException

from ..deps import AdminUser, DBSession, TenantId
from ..services.llm_service import (
    ChatRequest,
    ChatResponse,
    AgentPreview,
    chat,
    create_agent,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/admin/llm", tags=["Agent Builder"])


@router.post("/chat", response_model=ChatResponse)
async def llm_chat(
    request: ChatRequest,
    admin: AdminUser,
    tenant_id: TenantId,
    db: DBSession,
) -> ChatResponse:
    """
    Chat with the LLM to build an agent configuration.
    
    The LLM will guide the admin through the process of defining
    an agent's properties (name, greeting, voice, etc.).
    
    When the agent config is ready, the response will include
    `agent_preview` with the extracted configuration.
    """
    logger.info(
        "[llm_routes] Chat request",
        extra={
            "admin_id": str(admin.id),
            "tenant_id": str(tenant_id),
            "message_count": len(request.messages),
        }
    )
    
    try:
        response = await chat(request)
        return response
    except Exception as e:
        logger.error(f"[llm_routes] Chat failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/create-agent")
async def create_agent_from_preview(
    preview: AgentPreview,
    admin: AdminUser,
    tenant_id: TenantId,
    db: DBSession,
) -> dict:
    """
    Create an agent from the preview configuration.
    
    This is called after the admin confirms the agent config
    generated by the LLM chat.
    """
    logger.info(
        "[llm_routes] Create agent request",
        extra={
            "admin_id": str(admin.id),
            "tenant_id": str(tenant_id),
            "agent_name": preview.name,
        }
    )
    
    if not preview.name:
        raise HTTPException(status_code=400, detail="Agent name is required")
    
    try:
        result = await create_agent(preview)
        
        if result.get("status") == "error":
            raise HTTPException(status_code=500, detail=result.get("message"))
        
        logger.info(f"[llm_routes] Agent created: {result}")
        return result
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"[llm_routes] Create agent failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))
